print ("Hisssss...")
print ('Oink!..')
print ('Meow!!...')
print ('Roar....')

#using sep separator and end to print function..
print ("I","am","going","to","draw","an arrow",sep="_",end="_*_")
print("with the help of codes")

print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")
print("    *\n   * *\n  *   *\n *     *\n***   ***\n  *   *\n  *   *\n  *****")
print("    *         *\n   * *       * *\n  *   *     *   *\n *     *   *     *\n***   *** ***   ***\n  *   *     *   *\n  *   *     *   *\n  *****     *****")
print("        *\n      *   *\n    *       *\n  *           *\n* * *       * * *\n    *       *\n    *       *\n    * * * * *")
